name: unittests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.13.3
    - name: Plain Python unit tests under scripts
      run: |
        cd $GITHUB_WORKSPACE/scripts/
        python3 unittests.py
